spring:
  application:
    name: spring-mvc-simple-demo
  datasource:
    url: jdbc:mysql://172.17.18.6:3306/sakila?useSSL=false # Home server
    username: reconov
    password: reconov
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  logging:
    file:
      name: /Coding/Logging/${spring.application.name}/log