spring:
  application:
    name: spring-cloud-client
  jackson:
    serialization:
      write-dates-as-timestamps: false
logging:
  file:
    name: /Coding/Logging/${spring.application.name}/log
server:
  port: 3000
base-service-url: http://localhost:4000/api