spring:
  application:
    name: spring-cloud-client
server:
  port: 0 # auto-magically assign me available ones => for dynamic addressing and load balancing
base-service-url: http://localhost:4000/api # static server address
#
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${random.uuid}