spring:
  application:
    name: spring-cloud-server
  datasource:
    url: jdbc:mysql://172.17.18.6:3306/sakila?useSSL=false # Home server
    username: reconov
    password: reconov
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  file:
    name: /Coding/Logging/${spring.application.name}/log
server:
  port: 0 # dynamically auto-magically assign free port - This will help with Load balancing
#  port: 4000
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid} # unique for each instance