spring:
  application:
    name: spring-cloud-server
  datasource:
    url: jdbc:mysql://172.17.18.6:3306/sakila?useSSL=false # Home server
    username: reconov
    password: reconov
server:
  port: 0 # dynamically auto-magically assign free port - This will help with Load balancing
          # Having multiple instances of the same service
#  port: 4000
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid} # unique for each instance